minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
blockExoticSubdeps: true
saveExact: true

allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@supabase/cli-darwin-arm64@2.118.0"
  - "@supabase/cli-darwin-x64@2.118.0"
  - "@supabase/cli-linux-arm64-musl@2.118.0"
  - "@supabase/cli-linux-arm64@2.118.0"
  - "@supabase/cli-linux-x64-musl@2.118.0"
  - "@supabase/cli-linux-x64@2.118.0"
  - "@supabase/cli-windows-arm64@2.118.0"
  - "@supabase/cli-windows-x64@2.118.0"
  - supabase@2.118.0
